### ISSUE TITLE
使用vite构建后出现TypeError: undefined is not a non-null object

### ISSUE THREAD

**Issue by ivistang** [6tail/lunar-typescript#5]
我猜测是commonJS的兼容性问题。
具体报错在`Object.defineProperty(LunarTime, "__esModule", { value: true });`处，提示`LunarTime`是`undefined`。
目前我使用lunar-javascript构建则不会出现此问题。

**Comment by ikangjie** [comment]
我也出现了这样的问题，请问你有解决的方案了吗

**Comment by ivistang** [comment]
我的解决方案是直接从lunar-javascript调取函数，然后从lunar-typescript源码获取函数的interface。

**Comment by 6tail** [comment]
v1.2.23导出了LunarTime，之前遗漏了。
