### ISSUE TITLE
TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by JawilX** [6tail/lunar-typescript#6]
环境： vite 4.1.4, typescript 4.9.5
不知道为什么开发时没问题，build后会报这个错误，错误定位到了下面这段代码
```
Object.defineProperty(St, "__esModule", {
        value: !0
}),
```

**Comment by 6tail** [comment]
@JawilX 
原因是浏览器不支持build生成的js语法，我试了下，可以通过以下方式解决：

安装@vitejs/plugin-legacy：
`pnpm i @vitejs/plugin-legacy -D`

在vite.config.ts中配置如下：
`import { defineConfig } from 'vite'`
`import vue from '@vitejs/plugin-vue'`
`import legacyPlugin from '@vitejs/plugin-legacy'`

`export default defineConfig({`
`  plugins: [`
`    vue(),`
`    legacyPlugin({`
`      targets:['chrome 52'],`
`      additionalLegacyPolyfills:['regenerator-runtime/runtime']`
`    })`
`  ],`
`})`

最后：
`pnpm run build`

**Comment by iamwangqing** [comment]
> @JawilX 原因是浏览器不支持build生成的js语法，我试了下，可以通过以下方式解决：
> 
> 安装@vitejs/plugin-legacy： `pnpm i @vitejs/plugin-legacy -D`
> 
> 在vite.config.ts中配置如下： `import { defineConfig } from 'vite'` `import vue from '@vitejs/plugin-vue'` `import legacyPlugin from '@vitejs/plugin-legacy'`
> 
> `export default defineConfig({` ` plugins: [` ` vue(),` ` legacyPlugin({` ` targets:['chrome 52'],` ` additionalLegacyPolyfills:['regenerator-runtime/runtime']` ` })` ` ],` `})`
> 
> 最后： `pnpm run build`

我也出现了这个问题， vite^4.1.4，typescript^4.9.4，lunar-typescript^1.3.0，使用了@vitejs/plugin-legacy之后还是出现上面那个报错

**Comment by winson52u** [comment]
遇到同样的问题， vite^4.1.4，typescript^4.5.5，lunar-typescript^1.3.0
使用了@vitejs/plugin-legacy之后还是一样报错

**Comment by 6tail** [comment]
@JawilX @winson52u @WangQ98 v1.3.1应该是修复了，也不再需要@vitejs/plugin-legacy。

**Comment by winson52u** [comment]
1.3.1已解决。感谢。

**Comment by AuYuHui** [comment]
同样遇到了这个问题，升级后解决了

**Comment by JawilX** [comment]
> @JawilX @winson52u @WangQ98 v1.3.1应该是修复了，也不再需要@vitejs/plugin-legacy。

感谢，之前尝试@vitejs/plugin-legacy时碰到不兼容bigint的问题，一直没搜到解决方法，现在不用想这个问题了
